[package]
name = "redis-populate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.25.3"
redis_ts = "0.5.4"
sysinfo = "0.30.11"
tokio = "1.37.0"
chrono = "0.4.38"